'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AudioPlayer, {
  useAudioPlayer,
} from '../components/AudioPlayer/AudioPlayer';
import { AUDIO_URL } from '../Utils/constants';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { audioRef, pauseAudio, playAudio, isAudioPlaying } = useAudioPlayer();
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          {children}
          <div className="flex flex-row justify-center">
            <AudioPlayer
              autoPlay={false}
              ref={audioRef}
              url={AUDIO_URL}
              controls={false}
              loop={true}
            ></AudioPlayer>
          </div>
        </>
      </body>
    </html>
  );
}
